### ISSUE TITLE
[Feature Request]Allow "sync contacts" check/uncheck option at startup for first/initial account as well.

### ISSUE THREAD

**Issue by vdbhb59** [Telegram-FOSS-Team/Telegram-FOSS#416] opened 2020-06-12 04:42 UTC
Hi Team,
It would be good to have the "sync contacts" checkbox available when we are adding the first/initial account, just like it does in the second or third account addition. Many like me, do not like to have their accounts synced due to privacy reasons, and by the time we reach to settings to disable it, it is synced already (taking into consideration, the internet connectivity is still ON, for whatever valid reason, when the TG setup is being done, or taking that few are not aware of the option, as new users).

This will be a good option to have. Kindly take this into consideration.

**Comment by vdbhb59** [comment] 2020-08-25 13:04
No use raising any issues. At least give a holding response..

**Comment by anupritaisno1** [comment] 2020-08-25 16:13
I don't see the issue. Don't grant the contacts permission?

**Comment by vdbhb59** [comment] 2020-08-26 06:32
@anupritaisno1 Are you serious? Did you even read what I wrote?
Irrespective of whether one grants sync permission or not, the client auto syncs the moment one logs in (initial client). This is NOT an issue, this is a feature request of allowing sync contacts checkbox like it is allowed when adding a second account.
I clearly explained and you are being rude for no apparent reason. Please read and then communicate. Courtesy..

**Comment by vdbhb59** [comment] 2020-08-26 06:36
Just so that you understand, I added Feature Request tag.

**Comment by timmwille** [comment] 2021-02-04 18:15
hello everyone → a friend of mine just pointed me at this specific problem: first setup on smartphone of Telegram FOSS it opens a request to give access to contacts and synch them to the (hopefully) encrypted server. Whenever the App opens, this pops up each time again. So one could accidentally hit "OK" although the decision not to synch has been made a long time ago :)

→ if someone does not want this it would be nice to have a simple checkbox while setup to check/uncheck this option (well also later check/uncheck) would be good in case one decides otherwise :) 

thx for raising this privacy topic @vdbhb59

**Comment by vdbhb59** [comment] 2021-02-04 19:01
> 
> 
> hello everyone → a friend of mine just pointed me at this specific problem: first setup on smartphone of Telegram FOSS it opens a request to give access to contacts and synch them to the (hopefully) encrypted server. Whenever the App opens, this pops up each time again. So one could accidentally hit "OK" although the decision not to synch has been made a long time ago :)
> 
> → if someone does not want this it would be nice to have a simple checkbox while setup to check/uncheck this option (well also later check/uncheck) would be good in case one decides otherwise :)
> 
> thx for raising this privacy topic @vdbhb59

It is open for long, and no one cares I believe. I was replied in a rude manner earlier, and TG-FOSS team is behaving exactly how TG does, do not reply, and do not care. Only illogical and stupid stuff get IN, not PRIVACY friendly in reality.

**Comment by thermatk** [comment] 2021-02-04 19:06
But why do you give contacts sync permission in the first place?
I can't reproduce, I install the app, don't give the permission when asked, all good
:/

**Comment by timmwille** [comment] 2021-02-04 20:07
> > hello everyone → a friend of mine just pointed me at this specific problem: first setup on smartphone of Telegram FOSS it opens a request to give access to contacts and synch them to the (hopefully) encrypted server. Whenever the App opens, this pops up each time again. So one could accidentally hit "OK" although the decision not to synch has been made a long time ago :)
> > → if someone does not want this it would be nice to have a simple checkbox while setup to check/uncheck this option (well also later check/uncheck) would be good in case one decides otherwise :)
> > thx for raising this privacy topic @vdbhb59
> 
> It is open for long, and no one cares I believe. I was replied in a rude manner earlier, and TG-FOSS team is behaving exactly how TG does, do not reply, and do not care. Only illogical and stupid stuff get IN, not PRIVACY friendly in reality.

I think sometimes People just need to understand the Problem in detail, I hope for the best

**Comment by timmwille** [comment] 2021-02-04 20:11
> But why do you give contacts sync permission in the first place?
> I can't reproduce, I install the app, don't give the permission when asked, all good
> :/

Ah so this might be causing the pop-up? so a clean new install would solve it? 

So far I understood, when ever you try to enter contacts or you fully close the app (also in the background) and start it again you're presented with the Pop-Up 

But sure I'll further investigate, from what I could find it is not possible to stop, when it starts asking (might be caused by an earlier "OK" so the question is how to stop it)

**Comment by timmwille** [comment] 2021-02-04 21:32
ok tested: so after the install you HAVE to allow Telegram to access your call list to automatically input the login code send (also strange, that it does only provide "OK" and does not allow me to manually do this via SMS, but that's another question for another time). So you can only press "OK" and after that it also asks you to activate the synch and access contacts with the option reject/later → and always asks again when the program was closed and opened again

**Comment by timmwille** [comment] 2021-02-04 21:35
> But why do you give contacts sync permission in the first place?
> I can't reproduce, I install the app, don't give the permission when asked, all good
> :/

did you test also with closing the program and/or starting a chat or go to "contacts" and then it also does not pop-up? this would mean different behaviour on different devices/OS → I'm currently on LineageOS

**Comment by Younes-L** [comment] 2021-02-06 06:45
@vdbhb59 @timmwille tldr: telegram can't access your contacts regardless of what the app says, as long as the system permission to access contacts is denied.

There seems to be confusion about what a permission means in this thread.
`Contacts` permission ≠ option named `Sync contacts`
* Permissions are android settings, they are not controlled by any app. When you talk about permissions, people understand that you are referring to android settings.
   Permissions look like this : ![Screenshot_20210206-073429_cropped](https://user-images.githubusercontent.com/23421600/107111156-ea715b00-684d-11eb-83f7-c468eed6dcd9.png)

* Meanwhile you refer to the telegram setting named `sync contacts.` This is not a permission, just a setting inside the app.
   This telegram option looks like this : ![Screenshot_20210206-073502_cropped](https://user-images.githubusercontent.com/23421600/107111168-ffe68500-684d-11eb-8b85-be913de25107.png)

* This particular telegram setting (sync contacts) does nothing, whether it's ON or OFF, **unless** you also grant the **system permission** to access contacts.

By default, on a fresh install, the permission to access contacts is OFF, just like all other permissions.
By default, on a first login, the telegram option to sync contacts is ON, but this doesn't matter, because the permission to access contacts is OFF. The app can't sync contacts anyway because it can't see them.

Now to fix your problem @vdbhb59 : no need to do anything, as there's no issue. You can safely keep the ☑️   "sync contacts"  checkbox checked, during first login, or when adding accounts, it does not matter. What matters is whether or not you grant the permission to access contacts in Android system settings.


To fix your problem @timmwille : this is a real problem but thankfully it's completely caused by user error.
Telegram will only ask you to give it access to contacts if you turn on the "sync contacts" option in telegram settings.
Turn OFF "sync contacts" in settings, and telegram will stop asking you every time.
Telegram only asks you because as far as the app is concerned, you (the user) *want* to sync contacts. Otherwise you wouldn't keep the "sync contacts" option enabled, right ?

You'll see a similar behaviour if you deny permission to access microphone, for example, then you try to record a voice note. Telegram will then ask you to give it access to microphone, of course because you pressed the microphone button.

Doing things like uninstall , reinstall , wipe data , reset , etc will not help. @timmwille the popup is a result of telegram options inside telegram settings, they are not affected by uninstall/reinstall.

**Comment by timmwille** [comment] 2021-02-19 22:09
thx @Younes-L I'll pass it over and let you know if it solved it (thx for your patient and detailed answer!)

**Comment by timmwille** [comment] 2021-02-19 22:21
solved → it was the not turned of security option in the settings of Telegram. thank you, from my side this can be closed now

**Comment by rustforfuture** [comment] 2021-08-13 15:55
> But why do you give contacts sync permission in the first place?
> I can't reproduce, I install the app, don't give the permission when asked, all good
> :/

What about those people that uses versions below marshmallow?

Best regards.

**Closed** 2023-06-06 09:06 UTC
