### ISSUE TITLE
Telegram store contacts in phonebook without any notifications and confirmation

### ISSUE THREAD

**Issue by referi** [Telegram-FOSS-Team/Telegram-FOSS#226] opened 2018-03-30 18:02 UTC
I installed a clean firmware AOSP without gaaps then f-droid and telegram. After that I found out that the telegram saved all the contacts in the phone book. All that is stored on the telegram servers he saved to the phone. Without any notifications and confirmations. It is not right. I do not want the program to decide for me. Fix it please.
Also you write that you store contacts on the server to notify when the new user will join. The phone can have a lot of contacts, for example, an Mike-electrician, a Kate-hairdresser, or a Marilin-prostitute. There is no need to receive notifications from them and there is no need to store their data on servers. Could you provide the choice of to keep or not?

**Comment by thermatk** [comment] 2018-03-30 22:39
Hi!
Simplistic patches are welcome, but on mm+ you're asked for explicit permission anyway, so the problem is slowly vanishing with each passing day

**Comment by Bubu** [comment] 2018-03-31 00:32
This is fixed in some upstream release for which we didn't get the source yet. (Or at least they added a delete option which more or less amounts to the same thing.)

So, @referi please try to convince telegram/durov to release the source code for newer versions.

**Comment by referi** [comment] 2018-03-31 06:58
Thanks guys I will try.

**Comment by thermatk** [comment] 2018-07-31 08:16
should be fixed in v4.9

**Closed by thermatk** 2018-07-31 08:16 UTC
Labels: upstream-source-please
