### ISSUE TITLE
Notifications not working on 5.13.1

### ISSUE THREAD

**Issue by nermolov** [Telegram-FOSS-Team/Telegram-FOSS#382] opened 2020-01-25 01:35 UTC
Notification service does not seem to be working on the latest version, only fetches notifications when the app is pulled into foreground. Works fine on 5.11.0

OnePlus 3T
Android 8.1.0 / LineageOS 15.1 microG

**Comment by Self-Perfection** [comment] 2020-01-25 10:50
Same here. Xiaomi Mi A1, Android 9,

Until 5.11 Telegram-FOSS showed persistent notification to keep app running in background. Version 5.13.1 doesn't show it, regardles of switch state in settings.

**Comment by thermatk** [comment] 2020-01-25 10:51
@Self-Perfection try to toggle the switch and report, it should fix it for now

**Comment by Self-Perfection** [comment] 2020-01-25 11:01
@thermatk I tried toggling Settings → Notification and Sound → Background Connection switch off and back on. Persistent notification have not appeared after that.

**Comment by hamiltonrn** [comment] 2020-01-25 17:02
Have the same problem, activate or deactivate the persistent notification changes nothing, that version simply don't keep a Telegram push connection. Everything is right with 5.11.

**Comment by thermatk** [comment] 2020-01-25 22:21
I could reproduce and (hopefully) fix the issue of push service being disabled when migrating, even though the persistent notification was showing. This could also be mitigated with the Settings toggle

From you reports there is a possibility of a second issue though, which I can't reproduce. Let's hope for v5.14

If v5.14 won't fix it as is, maybe it would be best to turn back to the times of TFOSS push being always on and kill the whole toggle logic across the codebase

**Comment by mad73923** [comment] 2020-01-26 09:04
Same problems here!

**Comment by H-A-L-I-S** [comment] 2020-01-26 13:30
@mad73923 I have the same problem. dev did confirm it and will fix is (hopefully) with the next update

**Comment by Self-Perfection** [comment] 2020-01-26 16:56
Aha, It seems I was confused and got it wrong.

**With version 5.13.1 missing persistent notification is intended behaviour, isn't it**? And notifications about new messages should appear with "Background Connection" switch on, though it might need toggling on/off.

Indeed, after toggling this switch notifications started to appear even if telegram-FOSS is not in foreground. I'm not sure how reliable they are though.

**Comment by thermatk** [comment] 2020-01-26 17:00
@Self-Perfection Missing persistent notification may only be explained by your own device settings, the notification appears in any case, even if push wasn't actually running in background 😅

**Comment by Coronarius** [comment] 2020-01-27 07:51
Yes, I can confirm that notification of version 5.13 is broken (Android 8.1). No sound and no popup on new massages. I don't change anyting in settings after update 5.11 -> 5.13 .

Please repair or revert to code of last working version 5.11 !

**Comment by fabmazz** [comment] 2020-01-27 15:52
I have the same problem, after installing latest version from F-Droid (5.13.1). I've just enabled the "Persistent notification" channel, but no notification shows up. I'm using Android 8.0 on Galaxy s7 (stock firmware)

**Comment by losuler** [comment] 2020-01-27 23:33
This is also happening with me, however the persistent notification (called "Push Notifications Service") is still there. Turning battery optimization to not optimized does not fix the issue, despite this not being needed for 5.11. This is on Android 10.

**Comment by DrPhilosophus** [comment] 2020-01-28 04:34
@losuler

**Comment by DrPhilosophus** [comment] 2020-01-28 04:36
@losuler Re-toggle background connection in settings -> notifications & sounds

**Comment by losuler** [comment] 2020-01-28 10:26
@DrPhilosophus This seems to have fixed it so far (tested for about half a day).

**Comment by jugendhacker** [comment] 2020-01-29 13:59
I also don't get notifications when Telegram wasn't open a few seconds ago. I'm on LOS 17 (so Android 10 too)

**Comment by fabmazz** [comment] 2020-01-29 14:53
I have found that I need to restart periodically the notification service,
by toggling "use notification service" off and on every once in a while.
This way it works, but I have to keep the notification of the notification
service showing.

Il Mer 29 Gen 2020, 14:59 jugendhacker <notifications@github.com> ha
scritto:

**Comment by devopsdeluxe** [comment] 2020-01-30 17:53
Version 5.14 on F-Droid has fixed the issues I was having with push notifications on 5.13.1.

**Closed** 2020-04-26 12:10 UTC

**Comment by nickbailuc** [comment] 2023-10-20 04:45
Why was this issue closed, I've never had Telegram FOSS show notiications on time (sometimes I get notified almost an hour later)
Had this problem on my S2 running Replicant, my Pixel XL, and now my Galaxy A53.

Every other app shows notifications within seconds (guessing they use Google play serices crap which polls everything at once afaik)

I'm finding complaints about this issue ages ago

I tried messing with the settings, including the 'keep Telegram running in the background' and all that.

Is there a fix anyone is aware of? 

The current version of T FOSS is 10.09, will downgrading to version 5.11 fix the issue once and for all? I dont mind downgrading, would rather have a functional app than 'the latest thing', my only concern and reason I havent tried that yet is security

**Comment by nickbailuc** [comment] 2023-10-20 04:46
P.S.
Is there any way to force Telegram FOSS to stay online 24/7 or emulate that. I don't care if it drains the battery more, I have a portable charger if I need, and half the time im working near a charger anyway
