### ISSUE TITLE
Sync issue with 4.9.1a (?)

### ISSUE THREAD

**Issue by samoht0** [Telegram-FOSS-Team/Telegram-FOSS#289] opened 2019-01-25 17:33 UTC
I'm facing a severe sync issue with 4.9.1a. Can reproduce it like that:
* Clean install of 4.9.1a, so all settings on default and no cached files/chats
* Starting app and registering session with code
* Should present the list of current conversations, but just a spinning wheel or a note, that there're no conversations, comes up
* New messages are only coming in while running the app (to be clear: messages that arrived on the server while app was not running do *not* appear at all)

Clean install of 4.9.1 is syncing the list of current conversations after registering just fine. New messages are arriving no matter what.
Same results on two devices (SLIM6).

**Comment by MatiasConTilde** [comment] 2019-01-25 18:15
duplicate of #288

**Closed** 2019-01-25 18:17 UTC
