### ISSUE TITLE
Boot loop after upgrade from 4.2.1 (1043) universal to 4.6.0 

### ISSUE THREAD

**Issue by danjde** [Telegram-FOSS-Team/Telegram-FOSS#207] opened 2018-01-02 16:08 UTC
Hi Friends,
Using Cyanogenmod 12.1-20150518-UNOFFICIAL-s3ve3g (Android version 5.1.1) on Samsung Galaxy S3 Neo, I've upgraded using F-Droid from 4.2.1 (1043) universal to 4.6.0 and during the upgrade process the phone has gone into boot loop.
I've solved restoring a previous TWRP image.

Thanks

**Comment by Sudokamikaze** [comment] 2018-01-02 16:49
Capture logs. logcat/dmesg

**Comment by spanktastic2120** [comment] 2018-01-04 03:07
I have this issue too and I'm 99% sure that the problem is the same as the one listed here ( https://github.com/yeriomin/YalpStore/issues/316 ) with yalp store and davdroid. "It's a bug in CyanogenMod / LineageOS, triggered by using aapt2 to build apk files."

**Comment by thermatk** [comment] 2018-01-04 12:00
The fix would be bumping build tools?
We can retag again after testing, considering fdroid buildserver fails to build the latest hotfix release since the 17.12.17 already 😞

**Comment by thermatk** [comment] 2018-01-04 13:16
this should fix it
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/4c15f92b440e680be9f5e99384bad123f3e44b4e

**Comment by r4sas** [comment] 2018-01-10 16:26
@thermatk, when 4.6a will be published at fdroid?

**Comment by thermatk** [comment] 2018-01-10 16:59
@r4sas 
https://gitlab.com/fdroid/fdroidserver/issues/437
not out fault, will eventually be fixed 👍

**Comment by ZJaume** [comment] 2018-01-16 09:24
I don't know if it is related. Version 4.6 sometimes causes reboots on my phone when openning images. And yesterday that reboot turned into a bootloop.

**Comment by r4sas** [comment] 2018-01-21 23:28
Regrading to current issue and [this](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/209#issuecomment-358067712) comment, I confirming that fix works.

**Comment by thermatk** [comment] 2018-02-07 13:31
Update released, should be fixed

**Closed by thermatk** 2018-02-07 13:31 UTC
Labels: help, upstream-bug

**Comment by danjde** [comment] 2018-02-16 19:03
Confirm, problem solved using 4.6.0a.

Thanks!!
